anastruct/fem/system.py

A simple change to yield Shear forces, in order to design rc beams and columns.

Added Q forces for elements

---

anastruct/fem/node.py
anastruct/fem/postprocess.py
anastruct/fem/system.py
anastruct/fem/system_components/util.py
anastruct/fem/tests/test.py

Fix ensure_single_hinge()

---

anastruct/fem/system.py
anastruct/fem/tests/test.py

Fixes #41 
(And my black desperately wants to autoformat line 627 there even though I didn't touch it...)

Fix add_multiple_elements() stability error

---

anastruct/fem/system.py
anastruct/fem/tests/test.py

Fix linear spring supports

---

anastruct/fem/plotter/mpl.py

Fixes #60 
Fix displayed max displacement per @Leuck's solution

Consider Free Body Displacement in Max Deflection Plot Label

---

anastruct/fem/elements.py
anastruct/fem/system.py
anastruct/fem/system_components/util.py

Fix a bunch of typing issues

---

setup.py

Include anastruct.sectionbase data files

---

anastruct/basic.py
anastruct/fem/system.py

Fixes https://github.com/ritchie46/anaStruct/issues/90

Import ABC from collections.abc for Python 3.10 compatibility.

---

requirements.txt

Last version to support python 3.7

Bump matplotlib to v3.5.3

---

anastruct/fem/system.py

Fixes #98 . Thanks @ghylander!

Fix bug with specifying direction of q_load

---

anastruct/fem/tests/test.py
anastruct/fem/util/load.py

Fixes #87 . Thanks to @RichardWhitfield for the general fix!

Fix Q-loads in LoadCases

---

doc/source/examples.rst

Fixes #80 . Thanks, @ablundon!

el.angle, not el.ai in example

---

anastruct/fem/system.py

Only assert non-None axial element results for truss elements

---

anastruct/fem/system.py

Add error message if point load applied at inclined roller

---

anastruct/fem/elements.py

Also add the q_loads in load combinations

---

tests/test_e2e.py

- add cantilever beam with UDL validation

Cantilever beam w UDL validation

---

.github/workflows/test.yaml
.vscode/extensions.json
.vscode/settings.json
MANIFEST.in
anastruct/basic.py
anastruct/cython/basic.py
anastruct/fem/cython/elements.py
anastruct/fem/elements.py
anastruct/fem/examples/ex_1_2.py
anastruct/fem/examples/ex_22_loadcombination_doc.py
anastruct/fem/examples/ex_7_rotational_spring.py
anastruct/fem/node.py
anastruct/fem/plotter/element.py
anastruct/fem/plotter/mpl.py
anastruct/fem/plotter/null.py
anastruct/fem/plotter/values.py
anastruct/fem/postprocess.py
anastruct/fem/system.py
anastruct/fem/system_components/assembly.py
anastruct/fem/system_components/util.py
anastruct/fem/util/load.py
anastruct/material/profile.py
anastruct/material/units.py
anastruct/sectionbase/properties.py
anastruct/sectionbase/sectionbase.py
anastruct/sectionbase/units.py
anastruct/vertex.py
mypy.ini
pyproject.toml

Typing was already present in system.py. This adds typing throughout all of anastruct, and also makes the typing stricter

Add almost-strict typing to all of anastruct

---

anastruct/fem/system.py

Fix regression in find_node_id() with typeof vertex == Vertex

---

doc/source/getting_started.rst

Add EA and EI values to element creation, so results of the code in the "Getting Started" page match the images showned (Shear, Bending and Displacement diagrams)

Add EA and EI values to element creation

---

.github/workflows/release.yaml
.github/workflows/test.yaml
_custom_build.py
anastruct/fem/examples/ex_22_loadcombination_doc.py
anastruct/fem/plotter/mpl.py
anastruct/fem/plotter/values.py
anastruct/vertex.py
pyproject.toml

Now that they exist in matplotlib 3.8

Enable matplotlib type checks in mypy

---

anastruct/fem/system.py

which is equivalent to add_element_grid() but uses Vertex'es, like every other function we have.
Also, make add_element_grid() just call our new add_sequential_elements() function.

Create new add_sequential_elements() function

---

anastruct/fem/examples/ex_14.py
anastruct/fem/examples/ex_15.py
anastruct/fem/examples/ex_16.py
anastruct/fem/system.py

Return a list of dicts from get_node_results_system() & get_node_displacements()

---

anastruct/fem/examples/water_acc.ipynb
doc/source/examples.rst

Remove non-existent plot_backend param from examples

---

anastruct/fem/plotter/mpl.py

Fixed #358
